### ISSUE TITLE
Do you have to package your app a certain way for this to work?

### ISSUE THREAD

**Issue by rchrd2** [onassar/ElectronFileOpener#1]
I can't seem to get this to work. Do you have to package your app a certain way for this to work?

Is anything else besides this code needed?

Thank you.

**Comment by onassar** [comment]
Not especially; can you post your code?
Does your init function/callback receive any data?

**Comment by rchrd2** [comment]
I can't even drag anything into the Dock icon. With other apps, the app icon dims, and a tooltip appears. With my app, there's no roll over state, and it won't let me drop the file on there.

```
var electron = require("electron");
var Menu = electron.Menu;
var app = electron.app;
var menu = require("./menu");
var windows = require("./windows");

// Attempt to bind file opening #1
var fileOpener = require('./electron-file-opener.js');
fileOpener.init(function(filePaths) {
  console.log(filePaths);
  windows.create(undefined, filePaths);
});

// Attempt to bind file opening #2
app.on('will-finish-launching', () => {
  // Event fired When someone drags files onto the icon while your app is running
  app.on("open-file", (event, file) => {
    windows.create(undefined, file);
    event.preventDefault()
  });
});
```


Do you actually have to build the app, or will `electron . ` work?

**Comment by onassar** [comment]
Ahh gotcha. It's been a minute since I was messing around with Electron stuff, but I do believe you need to tell your Electron app which kinds of files can be opened by it. From what I recall, that's how it knows to have the Dock icon dim and make those files selectable.

I'm using Electron Forge to build my app, and within the config file for my app, I define an `extendInfo` plist file which tells Electron that any images can be opened using my app.

My `Info.plist` file looks as follows:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDocumentTypes</key>
  <array>
    <dict>
      <key>CFBundleTypeExtensions</key>
      <array>
        <string>png</string>
      </array>
      <key>CFBundleTypeIconFile</key>
      <string>electron.icns</string>
      <key>CFBundleTypeMIMETypes</key>
      <array>
        <string>image/png</string>
      </array>
      <key>CFBundleTypeName</key>
      <string>PNG image</string>
      <key>CFBundleTypeOSTypes</key>
      <array>
        <string>PNGf</string>
      </array>
      <key>CFBundleTypeRole</key>
      <string>Editor</string>
    </dict>
    <dict>
      <key>CFBundleTypeExtensions</key>
      <array>
        <string>jpg</string>
        <string>jpeg</string>
      </array>
      <key>CFBundleTypeIconFile</key>
      <string>electron.icns</string>
      <key>CFBundleTypeMIMETypes</key>
      <array>
        <string>image/jpeg</string>
      </array>
      <key>CFBundleTypeName</key>
      <string>JPEG image</string>
      <key>CFBundleTypeOSTypes</key>
      <array>
        <string>JPEG</string>
      </array>
      <key>CFBundleTypeRole</key>
      <string>Editor</string>
    </dict>
    <dict>
      <key>CFBundleTypeExtensions</key>
      <array>
        <string>gif</string>
      </array>
      <key>CFBundleTypeIconFile</key>
      <string>electron.icns</string>
      <key>CFBundleTypeMIMETypes</key>
      <array>
        <string>image/gif</string>
      </array>
      <key>CFBundleTypeName</key>
      <string>GIF image</string>
      <key>CFBundleTypeOSTypes</key>
      <array>
        <string>GIFf</string>
      </array>
      <key>CFBundleTypeRole</key>
      <string>Editor</string>
    </dict>
  </array>
</dict>
</plist>
```

Here are a couple links for reference:
https://electronforge.io/config/electronPackagerConfig
https://github.com/electron-userland/electron-forge/issues/492

Hope that helps you get started!

**Comment by rchrd2** [comment]
Thank you!!! This really helps. I was completely lost.

I would suggest adding a point about this in the package README to save future developers.

I ended up using `electron-builder` (not sure if it's the best one), because it has a simple API:

```
electron-builder --config electron-builder-config.json
```

**electron-builder-config.json**
```
{
   "appId": "com.example.app",
   "files": ["**"],
   "fileAssociations": [
    {
        "ext": ["txt"],
        "name": "Plain Text",
        "role": "Editor"
    }
   ]
}
```

**Comment by rchrd2** [comment]
I created an example project for future reference: 

https://github.com/rchrd2/example-electron-file-association

Note, it does not use this library (electron-file-opener) for simplicity's sake,

**Comment by onassar** [comment]
Nice that's a pretty clean config file. I need(ed) forge a bunch of different things, and while having to create a plist file isn't ideal, it definitely works within my workflow. I'll keep `electron-builder` in mind for the future thought :)
